name        : tmux
version     : 2.0
release     : 3
source     :
    - https://github.com/tmux/tmux/releases/download/2.0/tmux-2.0.tar.gz : 795f4b4446b0ea968b9201c25e8c1ef8a6ade710ebca4657dd879c35916ad362
license     :
    - BSD
summary     : terminal multiplexer
builddeps   :
    - pkgconfig(libevent)
description : |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
    
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -d %installroot%/usr/share/bash-completion/completions
    install examples/bash_completion_tmux.sh %installroot%/usr/share/bash-completion/completions/tmux
