name       : tmux
version    : '2.6'
release    : 12
source     :
    - https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz : b17cd170a94d7b58c0698752e1f4f263ab6dc47425230df7e53a6435cc7cd7e8
license    : BSD
component  : system.utils
summary    : terminal multiplexer
description: |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -d %installroot%/usr/share/bash-completion/completions
    install $pkgfiles/tmux %installroot%/usr/share/bash-completion/completions/tmux
