name       : tmux
version    : 3.2a
release    : 18
source     :
    - https://github.com/tmux/tmux/releases/download/3.2a/tmux-3.2a.tar.gz : 551553a4f82beaa8dadc9256800bcc284d7c000081e47aa6ecbb6ff36eacd05f
license    : 0BSD
component  : system.utils
summary    : terminal multiplexer
description: |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -d %installroot%/usr/share/bash-completion/completions
    install $pkgfiles/tmux %installroot%/usr/share/bash-completion/completions/tmux
