name       : tmux
version    : 3.3a
release    : 20
source     :
    - https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz : e4fd347843bd0772c4f48d6dde625b0b109b7a380ff15db21e97c11a4dcdf93f
license    : 0BSD
component  : system.utils
summary    : terminal multiplexer
description: |
    tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
    to be accessed and controlled from a single terminal. tmux is intended to be a
    simple, modern, BSD-licensed alternative to programs such as GNU screen.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -d %installroot%/usr/share/bash-completion/completions
    install $pkgfiles/tmux %installroot%/usr/share/bash-completion/completions/tmux
